dependencies:
  - pip
  - pip:
    - absl-py==0.9.0
    - aiohttp==3.6.2
    - alembic==1.4.2
    - astor==0.8.1
    - async-timeout==3.0.1
    - atari-py==0.2.6
    - attrs==19.3.0
    - beautifulsoup4==4.9.0
    - cachetools==4.1.0
    - cffi==1.14.0
    - chardet==3.0.4
    - click==7.1.2
    - cloudpickle==1.3.0
    - colorama==0.4.3
    - configparser==5.0.0
    - databricks-cli==0.10.0
    - dm-tree==0.1.5
    - docker==4.2.0
    - entrypoints==0.3
    - filelock==3.0.12
    - flask==1.1.2
    - future==0.18.2
    - gast==0.2.2
    - gitdb==4.0.5
    - gitpython==3.1.2
    - google==2.0.3
    - google-auth==1.14.1
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.2.0
    - gorilla==0.3.0
    - grpcio==1.28.1
    - gunicorn==20.0.4
    - gym==0.17.1
    - h5py==2.10.0
    - humps==0.2.2
    - idna==2.9
    - imageio==2.8.0
    - imageio-ffmpeg==0.4.1
    - importlib-metadata==1.6.0
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - lz4==3.0.2
    - mako==1.1.2
    - markdown==3.2.1
    - markupsafe==1.1.1
    - mlflow==1.8.0
    - multidict==4.7.5
    - numpy==1.18.4
    - oauthlib==3.1.0
    - opencv-python==4.2.0.34
    - opencv-python-headless==4.2.0.34
    - opt-einsum==3.2.1
    - pandas==1.0.3
    - pillow==7.1.2
    - procgen==0.9.4
    - prometheus-client==0.7.1
    - prometheus-flask-exporter==0.13.0
    - protobuf==3.11.3
    - py-spy==0.3.3
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyglet==1.4.11
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - python-editor==1.0.4
    - pytz==2020.1
    - pyyaml==5.3.1
    - querystring-parser==1.2.4
    - ray==0.8.4
    - redis==3.5.0
    - requests==2.23.0
    - requests-oauthlib==1.3.0
    - rsa==4.0
    - scipy==1.4.1
    - simplejson==3.17.0
    - six==1.14.0
    - smmap==3.0.4
    - soupsieve==2.0
    - sqlalchemy==1.3.13
    - sqlparse==0.3.1
    - tabulate==0.8.7
    - tensorboard==2.1.1
    - tensorboardx==2.0
    - tensorflow==2.1.0
    - tensorflow-estimator==2.1.0
    - termcolor==1.1.0
    - urllib3==1.25.9
    - websocket-client==0.57.0
    - werkzeug==1.0.1
    - wrapt==1.12.1
    - yarl==1.4.2
    - zipp==3.1.0
